/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Mon Jun 11 17:59:13 2018. */

#include "tx.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Txs_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, Txs, txs, txs, &Tx_fields),
    PB_LAST_FIELD
};

const pb_field_t Tx_fields[8] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, Tx, from, from, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, Tx, to, from, 0),
    PB_FIELD(  3, UINT64  , SINGULAR, STATIC  , OTHER, Tx, amount, to, 0),
    PB_FIELD(  4, UINT64  , SINGULAR, STATIC  , OTHER, Tx, fee, amount, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, Tx, nonce, fee, 0),
    PB_FIELD(  6, BYTES   , SINGULAR, CALLBACK, OTHER, Tx, signature, nonce, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, Tx, recovery, signature, 0),
    PB_LAST_FIELD
};

const pb_field_t TxDB_fields[5] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, TxDB, hash, hash, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, TxDB, blockHash, hash, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, TxDB, blockHeight, blockHash, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, TxDB, txNumber, blockHeight, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
