/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Mon Jun 11 17:59:13 2018. */

#ifndef PB_TX_PB_H_INCLUDED
#define PB_TX_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Txs {
    pb_callback_t txs;
/* @@protoc_insertion_point(struct:Txs) */
} Txs;

typedef struct _Tx {
    pb_callback_t from;
    pb_callback_t to;
    uint64_t amount;
    uint64_t fee;
    uint32_t nonce;
    pb_callback_t signature;
    uint32_t recovery;
/* @@protoc_insertion_point(struct:Tx) */
} Tx;

typedef struct _TxDB {
    pb_callback_t hash;
    pb_callback_t blockHash;
    uint32_t blockHeight;
    uint32_t txNumber;
/* @@protoc_insertion_point(struct:TxDB) */
} TxDB;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Txs_init_default                         {{{NULL}, NULL}}
#define Tx_init_default                          {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, 0}
#define TxDB_init_default                        {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define Txs_init_zero                            {{{NULL}, NULL}}
#define Tx_init_zero                             {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, 0}
#define TxDB_init_zero                           {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Txs_txs_tag                              1
#define Tx_from_tag                              1
#define Tx_to_tag                                2
#define Tx_amount_tag                            3
#define Tx_fee_tag                               4
#define Tx_nonce_tag                             5
#define Tx_signature_tag                         6
#define Tx_recovery_tag                          7
#define TxDB_hash_tag                            1
#define TxDB_blockHash_tag                       2
#define TxDB_blockHeight_tag                     3
#define TxDB_txNumber_tag                        4

/* Struct field encoding specification for nanopb */
extern const pb_field_t Txs_fields[2];
extern const pb_field_t Tx_fields[8];
extern const pb_field_t TxDB_fields[5];

/* Maximum encoded size of messages (where known) */
/* Txs_size depends on runtime parameters */
/* Tx_size depends on runtime parameters */
/* TxDB_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TX_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
